### ISSUE TITLE
Welcome Card Strange Behaviour

### ISSUE THREAD

**Issue by stripathi669** [dexafree/MaterialList#32]
I am using 2.0.1 version of your the library and have encountered a very strange behaviour when adding welcome cards.

I am creating a new welcome card using:

        SimpleCard card;
         card = new WelcomeCard(this);
        card.setTitle("Welcome!");
        card.setDescription("If you're a new user, we recommend you take the tutorial.");
        ((WelcomeCard) card).setSubtitle("Take a quick tour ?");
        ((WelcomeCard) card).setButtonText("Okay!");
        ((WelcomeCard) card).setBackgroundColorRes(R.color.primary);
        ((WelcomeCard) card).setDividerColor(getResources().getColor(R.color.primary_dark));
        ((WelcomeCard) card).setDescriptionColor(getResources().getColor(R.color.icons));
        card.setDismissible(true);
        ((WelcomeCard) card).setOnButtonPressedListener(new OnButtonPressListener() {
            @Override
            public void onButtonPressedListener(View view, Card card) {
                card.dismiss();
                Toast.makeText(MainActivity.this,"Coming Soon", Toast.LENGTH_LONG).show();
            }
    });

I am adding it to mListView using:

    mListView.add(card);
   

Very strangely, 
* Two welcome cards get added to my view instead of one. 
* I can't seem to be able to change the color of description text.

I have attached a screenshot for reference. 
![device-2015-01-22-042454](https://cloud.githubusercontent.com/assets/7647281/5847217/d337365a-a1f0-11e4-921e-fde07a814de0.png)

**Comment by dexafree** [comment]
Copied your exact same code (notice that now `card.dismiss()` is `mListView.remove(Card)`) and the result is

![Result](http://i.imgur.com/OzVxm70.jpg)

Weird bug...

**Comment by stripathi669** [comment]
Weird bug indeed. And yes, I am using Lollipop. Well, I am using temporary fix of adding two time, and removing one time. If I happen to to catch the problem, I will post here.

Also, I noticed that even in your testing, color of description text doesn't change. Is it so ?

**Comment by dexafree** [comment]
The change of the description color should be fixed in https://github.com/dexafree/MaterialList/commit/6f69318ef05bfb890c11bd78e57ab19097ff6b56

Version 2.0.3 should be in maven central within a few hours

**Comment by stripathi669** [comment]
Okay. Thankyou very much. This is a wonderful library.

You've been a great help.

**Comment by dexafree** [comment]
Thank you!

If you got more details to reproduce this strange issue, I will definitely take a look at it

**Comment by meanmee** [comment]
@stripathi669  How U get start with this library,i cann't compile it ,would u like to share your way that you compile it ,thank u very much.

**Comment by stripathi669** [comment]
I am assuming you've tried instructions in Readme.md file (that's how I did it) . So please let us know what platform are you using (Eclipse, Android Studio). If you're using studio, please post your compile error.

Also, It is my very humble request  to take this to a new thread, so that issues remain organised under appropriate titles.
